# Generated by Django 5.1.3 on 2026-02-14 01:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gasto",
            old_name="trip",
            new_name="viaje",
        ),
        migrations.RenameField(
            model_name="vehiculo",
            old_name="placa",
            new_name="placas",
        ),
        migrations.RemoveField(
            model_name="cargacombustible",
            name="costo",
        ),
        migrations.RemoveField(
            model_name="cargacombustible",
            name="fecha",
        ),
        migrations.RemoveField(
            model_name="cargacombustible",
            name="vehiculo",
        ),
        migrations.RemoveField(
            model_name="gasto",
            name="concepto",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="gastos_estimados",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="hora_salida",
        ),
        migrations.AddField(
            model_name="cargacombustible",
            name="costo_total",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cargacombustible",
            name="foto_ticket",
            field=models.ImageField(blank=True, null=True, upload_to="tickets/"),
        ),
        migrations.AddField(
            model_name="cargacombustible",
            name="precio_por_litro",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cargacombustible",
            name="viaje",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargas_diesel",
                to="fleet.trip",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gasto",
            name="descripcion",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="gasto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("CASETA", "Caseta"),
                    ("VIATICO", "Viático"),
                    ("MANIOBRA", "Maniobra"),
                    ("OTRO", "Otro"),
                ],
                default=0,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trip",
            name="fecha_regreso",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="economico",
            field=models.CharField(
                default=0, max_length=20, verbose_name="No. Económico"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cargacombustible",
            name="kilometraje",
            field=models.IntegerField(help_text="Odómetro al momento de la carga"),
        ),
        migrations.AlterField(
            model_name="chofer",
            name="licencia",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chofer",
            name="telefono",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gasto",
            name="fecha",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="trip",
            name="cliente",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trip",
            name="fecha_salida",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="modelo",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Incidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACCIDENTE", "Accidente"),
                            ("FALLA_MECANICA", "Falla Mecánica"),
                            ("DEMORA", "Demora"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha_reporte", models.DateTimeField(auto_now_add=True)),
                ("resuelto", models.BooleanField(default=False)),
                (
                    "viaje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fleet.trip"
                    ),
                ),
            ],
        ),
    ]
